---
version: "2.0"

services:
  app:
    image: dimokus88/kyveprotokol:0.3.0
    env:
     - "POOL=0" 
     - "MNEMONIC="
     - "STAKE="
     - "LINK_ARWEAVE_WALLET=https://drive.google.com/uc?export=download&id=***"
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 4Gi
        storage:
          size: 1Gi
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
