---
version: "2.0"

services:
  app:
    image: dimokus88/kyveprotokol:0.0.6
    env:
     - "AUTO_POOL=no" # yes - автоматическая смена пула включена; no - смена пула в ручном режиме через обновление развертиывания(рекомендуется)
     - "POOL=0" # 0 - пул Moonbeam; 1 - пул Avalanche // C-Chain; 3 - пул Bitcoin ; 4 - пул Solana ;5 - пул zilliqa
     - "MNEMONIC=mnemohic_kyve_wallet" # seed фраза от тестового кошелька с kyve
     - "STAKE=ammount_to_stake" # количество kyve в стейк
     - "MONIKER=Your_moniker" # имя ноды
     - "LINK_ARWEAVE_WALLET=link_to_arweave_wallet" #Используйте облако для передачи файла в контейнер, просто вставьте ссылку на файл кошелька. Use cloud disk for a send arweave.json, just paste link to wallet file. 
     - "LINK_KYVE_VERSION=https://github.com/KYVENetwork/evm/releases/download/v1.0.3/evm-linux.zip"
     - "LINK_KYVE_Bitcoin=https://github.com/kyve-org/bitcoin/releases/download/v0.0.0/kyve-bitcoin-linux.zip"
     - "LINK_KYVE_Solana=https://github.com/kyve-org/solana/releases/download/v0.0.0/kyve-solana-linux.zip"
     - "LINK_KYVE_zilliqa=https://github.com/kyve-org/zilliqa/releases/download/v0.0.0/kyve-zilliqa-linux.zip"
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 4Gi
        storage:
          size: 1Gi
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
