---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
     - "POOL=2" # 0-Moonbeam;1-Avalanche//C-Chain;3 -Bitcoin;4 -Solana;5-zilliqa;6-Near;7-Selo;8-Evmos EVM;9-Cosmos Hub;10-Injective;11-Evmos Cosmos;12-Axelar;13-Aurora;14-Cronos;15-Terra
     - "MNEMONIC=" # seed фраза от тестового кошелька с kyve.
     - "LINK_ARWEAVE_WALLET=" #Используйте облако для передачи файла в контейнер, просто вставьте ссылку на файл кошелька. Use cloud disk for a send arweave.json, just paste link to wallet file. 

    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/kyve/main/pool.sh | bash ' 

    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 3Gi
        storage:
          size: 30Gi
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
